// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type AuditLog struct {
	ID        string
	UserID    string
	Action    string
	Resource  string
	Timestamp time.Time
}

type Group struct {
	ID   string
	Name sql.NullString
}

type GroupsPermission struct {
	ID           int32
	GroupID      sql.NullString
	ResourceID   sql.NullInt32
	PermissionID sql.NullInt32
}

type Organization struct {
	ID       int32
	Name     sql.NullString
	ParentID sql.NullInt32
}

type Permission struct {
	ID   int32
	Name sql.NullString
	Code sql.NullString
}

type Resource struct {
	ID   int32
	Name sql.NullString
	Code sql.NullString
}

type Role struct {
	ID    string
	Name  sql.NullString
	Level sql.NullInt32
}

type User struct {
	ID        string
	FirstName sql.NullString
	LastName  sql.NullString
	Username  sql.NullString
	Email     sql.NullString
	Password  sql.NullString
	Avatar    sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Active    sql.NullInt16
	Flag      sql.NullInt32
}

type UsersGroup struct {
	ID      int32
	UserID  sql.NullString
	GroupID sql.NullString
}

type UsersOrganization struct {
	ID             int32
	UserID         sql.NullString
	OrganizationID sql.NullInt32
}

type UsersPermission struct {
	ID           int32
	UserID       string
	ResourceID   int32
	PermissionID int32
}

type UsersRole struct {
	ID     int32
	UserID sql.NullString
	RoleID sql.NullString
}
