// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: audit_logs.sql

package db

import (
	"context"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (id, user_id, action, resource) VALUES ($1, $2, $3, $4)
`

func (q *Queries) CreateAuditLog(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createAuditLog)
	return err
}

const getAllAuditLogs = `-- name: GetAllAuditLogs :many
SELECT id, user_id, action, resource, timestamp FROM audit_logs
`

func (q *Queries) GetAllAuditLogs(ctx context.Context) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, getAllAuditLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.Resource,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditLogsByUserID = `-- name: GetAuditLogsByUserID :many
SELECT id, user_id, action, resource, timestamp FROM audit_logs WHERE user_id = $1
`

func (q *Queries) GetAuditLogsByUserID(ctx context.Context) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, getAuditLogsByUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.Resource,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuditLog = `-- name: UpdateAuditLog :exec
UPDATE audit_logs
SET
    user_id = COALESCE($2, user_id),
    action = COALESCE($3, action),
    resource = COALESCE($4, resource),
    timestamp = COALESCE($5, timestamp)
WHERE id = $1
  AND (COALESCE($2, user_id) != user_id
         OR COALESCE($3, action) != action
         OR COALESCE($4, resource) != resource
         OR COALESCE($5, timestamp) != timestamp)
`

func (q *Queries) UpdateAuditLog(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, updateAuditLog)
	return err
}
